services:
  - type: web
    name: elevenlabs-chat
    env: docker
    buildCommand: ./build.sh
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8888 "app:asgi_app"
    envVars:
      - key: AGENT_ID
        value: ${AGENT_ID}
      - key: ELEVENLABS_API_KEY
        value: ${ELEVENLABS_API_KEY}
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: CAS_LOGIN_URL
        value: ${CAS_LOGIN_URL}