services:
  - type: web
    name: elevenlabs-chat
    env: python
    buildCommand: ./build.sh
    startCommand: python app.py
    envVars:
      - key: AGENT_ID
        value: ${AGENT_ID}
      - key: ELEVENLABS_API_KEY
        value: ${ELEVENLABS_API_KEY}
