services:
  - type: web
    name: elevenlabs-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: AGENT_ID
        value: your_agent_id
      - key: ELEVENLABS_API_KEY
        value: your_api_key